In [2]:
import numpy as np
np.__version__

'1.18.1'

In [10]:
a = np.array([1,2,3,4,5])
a
b = np.array((6,7,8))
print(type(a))
print(type(b))
print(a)
print(b)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[1 2 3 4 5]
[6 7 8]


In [11]:
c = np.arange(1,21,1)
d = np.linspace(1,21, num = 20, endpoint = False, retstep = False, dtype = None )
print(c)
print(d)
e = np.linspace(3.0, 11.0, num = 16, endpoint = True, retstep = True)
print(e)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]
(array([ 3.        ,  3.53333333,  4.06666667,  4.6       ,  5.13333333,
        5.66666667,  6.2       ,  6.73333333,  7.26666667,  7.8       ,
        8.33333333,  8.86666667,  9.4       ,  9.93333333, 10.46666667,
       11.        ]), 0.5333333333333333)


In [19]:
f = np.array([[1,2,3], [4,5,6]])
print(f)
print(f.shape)

g = np.array([[[1,2,3,4,5],[6,7,8,9,10]],
            [[1,2,3,4,5],[6,7,8,9,10]]])
print(g)
print(g.shape)
print(g.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]
(2, 2, 5)
3


In [24]:
h = np.zeros((8,2))
i = np.ones((8,2))
j =np.empty((2,2,2))
print(h)
print(i)
print(j)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[[1.28822975e-231 1.28822975e-231]
  [3.95252517e-323 0.00000000e+000]]

 [[0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]]]


In [28]:
k = np.random.rand(2,3)
print(k)
l = np.random.randn(8,2)
print(l)

[[0.43758721 0.891773   0.96366276]
 [0.38344152 0.79172504 0.52889492]]
[[ 0.76103773  0.12167502]
 [ 0.44386323  0.33367433]
 [ 1.49407907 -0.20515826]
 [ 0.3130677  -0.85409574]
 [-2.55298982  0.6536186 ]
 [ 0.8644362  -0.74216502]
 [ 2.26975462 -1.45436567]
 [ 0.04575852 -0.18718385]]


In [3]:
m = np.array([[1,2,3], [5,6,7]])
m[: , 1:]

array([[2, 3],
       [6, 7]])