In [1]:
import numpy as np

In [2]:
a = np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
b = a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
b[5] = 82
print(b)
print(a)

[ 0  1  2  3  4 82  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4 82  6  7]
 [ 8  9 10 11]]


In [6]:
print(b)
c = a.ravel(order = 'F')
print(c)

[ 0  1  2  3  4 82  6  7  8  9 10 11]
[ 0  4  8  1 82  9  2  6 10  3  7 11]


In [7]:
## a.reshape() np.reshape(a, shape) 
d = np.arange(18)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [8]:
d.reshape(6, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [9]:
np.reshape(np.arange(0, 50, 2), (5,-1))

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [10]:
e = np.arange(21)
e.resize((3,7), refcheck = True)
print(e)
e.flatten
e.resize((4,9), refcheck = False)
print(e)
e.flatten
e.resize(2)
print(e)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]]
[0 1]


In [11]:
f = np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,9]], [[2,4,6,4], [8,10,12,3], [5,6,7,2]]])
f

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 7,  8,  9,  9]],

       [[ 2,  4,  6,  4],
        [ 8, 10, 12,  3],
        [ 5,  6,  7,  2]]])

In [12]:
print(f.shape)
print(f.sum(axis = 0))
print(f.sum(axis = 1))
print(f.sum(axis = 2))

(2, 3, 4)
[[ 3  6  9  8]
 [12 15 18 10]
 [12 14 16 11]]
[[12 15 18 20]
 [15 20 25  9]]
[[10 22 33]
 [16 33 20]]


In [13]:
g = np.arange(18).reshape(3,-1)
g

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [14]:
h = g[:, np.newaxis,:]
print(h)


[[[ 0  1  2  3  4  5]]

 [[ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]]]


In [15]:
i = np.arange(10).reshape(5,2)
j = np.arange(8).reshape(4,2)
k = np.arange(15).reshape(5,3)

print(np.concatenate((i,j)))
print(np.concatenate((i,k), axis = 1))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]
 [0 1]
 [2 3]
 [4 5]
 [6 7]]
[[ 0  1  0  1  2]
 [ 2  3  3  4  5]
 [ 4  5  6  7  8]
 [ 6  7  9 10 11]
 [ 8  9 12 13 14]]


In [16]:
l = np.arange(0,30,3).reshape(5,2)
print(i)
print(l)
print("-------------")
print(np.stack((i,l), axis = 0))
print("--------------")
print(np.stack((i,l), axis = 1))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[ 0  3]
 [ 6  9]
 [12 15]
 [18 21]
 [24 27]]
-------------
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[ 0  3]
  [ 6  9]
  [12 15]
  [18 21]
  [24 27]]]
--------------
[[[ 0  1]
  [ 0  3]]

 [[ 2  3]
  [ 6  9]]

 [[ 4  5]
  [12 15]]

 [[ 6  7]
  [18 21]]

 [[ 8  9]
  [24 27]]]


In [17]:
print(np.hstack((i,l)))
print(np.vstack((i,l)))

[[ 0  1  0  3]
 [ 2  3  6  9]
 [ 4  5 12 15]
 [ 6  7 18 21]
 [ 8  9 24 27]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [ 0  3]
 [ 6  9]
 [12 15]
 [18 21]
 [24 27]]


In [18]:
m = np.arange(20).reshape(4,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [19]:
np.split(m, [2,4])

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([], shape=(0, 5), dtype=int64)]

In [20]:
np.split(m, [1,3])

[array([[0, 1, 2, 3, 4]]),
 array([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]])]

In [21]:
np.split(m, 4)

[array([[0, 1, 2, 3, 4]]),
 array([[5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]])]

In [22]:
n = np.arange(40).reshape(4,10)
n

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [23]:
np.hsplit(n, [1,2,3])

[array([[ 0],
        [10],
        [20],
        [30]]),
 array([[ 1],
        [11],
        [21],
        [31]]),
 array([[ 2],
        [12],
        [22],
        [32]]),
 array([[ 3,  4,  5,  6,  7,  8,  9],
        [13, 14, 15, 16, 17, 18, 19],
        [23, 24, 25, 26, 27, 28, 29],
        [33, 34, 35, 36, 37, 38, 39]])]

In [24]:
np.vsplit(n, 2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])]

In [25]:
n = np.arange(16)
for i in n:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [26]:
for i in n.reshape(2,8):
    print(i)

[0 1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14 15]


In [27]:
for i in n.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [32]:
o = np.random.randint(1,100,16)
print(o)
print(np.amax(o))
print(np.amin(o))
print("-------------")
p = o.reshape(2,8)
print(p)
print(np.amax(p, keepdims = True))
print(p.max(axis = 1))
print(np.amax(p, axis = 1))
print("-------------")
print(np.amin(p, axis = 0))
print(np.amin(p, axis = 1))
print(p.min(axis = 0))
print(p.min(axis = 1))

[10 58 13  9 10 54 81 64  7 29 87 76 24  1  6 39]
87
1
-------------
[[10 58 13  9 10 54 81 64]
 [ 7 29 87 76 24  1  6 39]]
[[87]]
[81 87]
[81 87]
-------------
[ 7 29 13  9 10  1  6 39]
[9 1]
[ 7 29 13  9 10  1  6 39]
[9 1]


In [35]:
np.random.seed(0)
q = np.random.randint(1,100, size = (8,2)) 
print(q)
print(np.argmax(q))
print(np.argmax(q, axis = 0))
print(np.argmax(q, axis = 1))
print("-----------")
print(q.argmax())
print("-----------")
print(np.argmin(q, axis = 0))

[[45 48]
 [65 68]
 [68 10]
 [84 22]
 [37 88]
 [71 89]
 [89 13]
 [59 66]]
11
[6 5]
[1 1 0 0 1 1 0 1]
-----------
11
-----------
[4 2]


In [41]:
np.random.seed(0)
r = np.random.randint(1,100,size = (5,4))
print(r)
print(r>64)
print(np.where(r > 64))
print(np.where(r > 64, "larger than 16", "smaller than 16"))

[[45 48 65 68]
 [68 10 84 22]
 [37 88 71 89]
 [89 13 59 66]
 [40 88 47 89]]
[[False False  True  True]
 [ True False  True False]
 [False  True  True  True]
 [ True False False  True]
 [False  True False  True]]
(array([0, 0, 1, 1, 2, 2, 2, 3, 3, 4, 4]), array([2, 3, 0, 2, 1, 2, 3, 0, 3, 1, 3]))
[['smaller than 16' 'smaller than 16' 'larger than 16' 'larger than 16']
 ['larger than 16' 'smaller than 16' 'larger than 16' 'smaller than 16']
 ['smaller than 16' 'larger than 16' 'larger than 16' 'larger than 16']
 ['larger than 16' 'smaller than 16' 'smaller than 16' 'larger than 16']
 ['smaller than 16' 'larger than 16' 'smaller than 16' 'larger than 16']]


In [42]:
## np.nonzero() == np.where( !=0)
np.random.seed(0)
s = np.random.randint(1,100,size = (8,2))
print(s)
print(np.nonzero(s))
print(np.where(s!=0))

[[45 48]
 [65 68]
 [68 10]
 [84 22]
 [37 88]
 [71 89]
 [89 13]
 [59 66]]
(array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7]), array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]))
(array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7]), array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]))


In [46]:
np.random.seed(0)
t = np.random.randint(1,88, size = (2,8))
print(t)
print(np.sort(t))
print(np.argsort(t))
print(t.argsort)
print('----------')
print(np.sort(t, axis = 0))
print(np.sort(t, axis = 1))
print('----------')
np.random.seed(0)
u = np.random.randint(1,100000, 10000)
print(u)
print(np.sort(u, kind = 'quicksort'))

[[45 48 65 68 68 10 84 22]
 [37 71 13 59 66 40 47 82]]
[[10 22 45 48 65 68 68 84]
 [13 37 40 47 59 66 71 82]]
[[5 7 0 1 2 3 4 6]
 [2 0 5 6 3 4 1 7]]
<built-in method argsort of numpy.ndarray object at 0x7fbdb5577e40>
----------
[[37 48 13 59 66 10 47 22]
 [45 71 65 68 68 40 84 82]]
[[10 22 45 48 65 68 68 84]
 [13 37 40 47 59 66 71 82]]
----------
[68269 43568 42614 ... 95405 37901 10246]
[   11    14    22 ... 99966 99976 99981]
