In [1]:
import numpy as np

In [2]:
np.add(28, 82)

110

In [10]:
a = np.arange(1,50, 10)
b = np.arange(51,100,10)
print(a,b)
print('-----------')
print(a + b)
print(np.add(a,b))
print('-----------')
print(a - b)
print(np.subtract(a,b))
print('-----------')
print(a*b)
print(np.multiply(a,b))
print('-----------')
print(a / b)
print(np.divide(a,b))
print('-----------')
print(a % b)
print(np.mod(a,b))

[ 1 11 21 31 41] [51 61 71 81 91]
-----------
[ 52  72  92 112 132]
[ 52  72  92 112 132]
-----------
[-50 -50 -50 -50 -50]
[-50 -50 -50 -50 -50]
-----------
[  51  671 1491 2511 3731]
[  51  671 1491 2511 3731]
-----------
[0.01960784 0.18032787 0.29577465 0.38271605 0.45054945]
[0.01960784 0.18032787 0.29577465 0.38271605 0.45054945]
-----------
[ 1 11 21 31 41]
[ 1 11 21 31 41]


In [20]:
c = np.arange(16)
cc = 3
d = np.arange(32)
e = c.reshape(1,16)
f = d.reshape(2,16)
print(c*cc)
print(e,f)
print(e + f)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]] [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]]
[[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
 [16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46]]


In [21]:
print(f.sum())
print(f.sum(axis = 0))
print(f.sum(axis = 1))

496
[16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46]
[120 376]


In [39]:
g = np.arange(10)
h = np.arange(0,100,10)
j = np.arange(5,10)
gg = g.reshape(2,5)
hh = h.reshape(2,5)
print(gg,"------",hh)
print(np.power(hh,gg))
print(j)
k = gg ** j
print(gg ** j)

[[0 1 2 3 4]
 [5 6 7 8 9]] ------ [[ 0 10 20 30 40]
 [50 60 70 80 90]]
[[                 1                 10                400
               27000            2560000]
 [         312500000        46656000000      8235430000000
    1677721600000000 387420489000000000]]
[5 6 7 8 9]
[[        0         1       128      6561    262144]
 [     3125     46656    823543  16777216 387420489]]


In [40]:
np.sqrt(k)

array([[0.00000000e+00, 1.00000000e+00, 1.13137085e+01, 8.10000000e+01,
        5.12000000e+02],
       [5.59016994e+01, 2.16000000e+02, 9.07492700e+02, 4.09600000e+03,
        1.96830000e+04]])

In [41]:
np.e

2.718281828459045

In [42]:
np.exp(1)

2.718281828459045

In [43]:
np.exp(np.arange(8))

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03])

In [49]:
print(np.log(100))
print(np.log10(100))
print(np.log2(32))
print(np.log(64)/np.log(8))
l = np.arange(1,6)
print(np.log(l))

4.605170185988092
2.0
5.0
2.0
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [54]:
m = np.array([4.65, 4.55, -7.57, 8, 4.5, -4.5])
## 四捨、五取最近偶數、六入，而非我們一般講的四捨五入。
print(np.round(m, decimals=1))
print(np.round(m, decimals=0))
print(np.rint(m))
print(np.trunc(m))
print(np.floor(m))
print(np.ceil(m))
print(np.fix(m))

[ 4.6  4.6 -7.6  8.   4.5 -4.5]
[ 5.  5. -8.  8.  4. -4.]
[ 5.  5. -8.  8.  4. -4.]
[ 4.  4. -7.  8.  4. -4.]
[ 4.  4. -8.  8.  4. -5.]
[ 5.  5. -7.  8.  5. -4.]
[ 4.  4. -7.  8.  4. -4.]


In [55]:
np.abs(m)

array([4.65, 4.55, 7.57, 8.  , 4.5 , 4.5 ])