In [1]:
import numpy as np

In [2]:
np.random.seed(0)
a = np.random.randint(1, 56, 8).reshape(2,4)
b = np.random.randint(1, 6, 4)
print(a)
print(b)
print("max,", np.maximum(a, b))
print("min,", np.minimum(a, b))
print("with nan,", np.minimum(a, [np.nan, 4, 5, np.nan]))

[[45 48 54  1]
 [ 4  4 40 10]]
[4 3 5 1]
max, [[45 48 54  1]
 [ 4  4 40 10]]
min, [[4 3 5 1]
 [4 3 5 1]]
with nan, [[nan  4.  5. nan]
 [nan  4.  5. nan]]


In [3]:
print(np.fmax(a, b))
print(np.fmin(a, [np.nan,np.nan,np.nan,np.nan]))
#遇到nan: maximum,min回傳nan; fmax,fmin回傳非nan值

[[45 48 54  1]
 [ 4  4 40 10]]
[[45. 48. 54.  1.]
 [ 4.  4. 40. 10.]]


In [4]:
print(np.nanmax([1,2,3,4,5,np.nan]))
print(np.nanmin([np.nan, np.nan, np.nan]))

5.0
nan


/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: All-NaN axis encountered
  


In [5]:
c = np.arange(1, 100, 5).astype('float32')##astype用意？
c

array([ 1.,  6., 11., 16., 21., 26., 31., 36., 41., 46., 51., 56., 61.,
       66., 71., 76., 81., 86., 91., 96.], dtype=float32)

In [6]:
print(np.percentile(c, [25,30,50]))
c[1] = np.nan
c[2] = np.nan
c[3] = np.nan

print("cc = ", c)
print("------comparison--------")
print(np.percentile(c, 75))
print(np.nanpercentile(c, 75))

[24.75 29.5  48.5 ]
cc =  [ 1. nan nan nan 21. 26. 31. 36. 41. 46. 51. 56. 61. 66. 71. 76. 81. 86.
 91. 96.]
------comparison--------
nan
76.0


In [7]:
d = np.array([1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86, 91, 93])
print(d)
print(np.quantile(d, 0.25))

e = np.array([23,  2,  1, np.nan,  9, 25, np.nan, 48, 43,  9, 35,  np.nan,  4,  9, np.nan,  3,  5, 25, 45, 13]).reshape(5, 4)
print(e)
print(np.nanquantile(e, 0.25, axis = 0, keepdims = True))

[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 93]
24.75
[[23.  2.  1. nan]
 [ 9. 25. nan 48.]
 [43.  9. 35. nan]
 [ 4.  9. nan  3.]
 [ 5. 25. 45. 13.]]
[[ 5.  9. 18.  8.]]


In [8]:
f = np.array([23,  2,  1, np.nan,  9, 25, np.nan, 
              48, 43,  9, 31,  np.nan]).reshape(3, 4)
print(np.mean(f))

nan


In [9]:
if np.isnan(np.mean(f)) == True :
    print('陣列中含有NaN，去除NaN後平均值為：', np.nanmean(f))
else:
    print('陣列中未含有NaN，平均值為：', np.mean(f))

陣列中含有NaN，去除NaN後平均值為： 21.22222222222222


In [10]:
g = np.arange(15).reshape(3,5)
print(g)
print(np.average(g, axis = 0, weights = [0.25, 0.75,1]))
print(np.average(g, axis = 1, weights = [0.25, 0.75,1,1,1]))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[ 6.875  7.875  8.875  9.875 10.875]
[ 2.4375  7.4375 12.4375]


In [11]:
np.random.seed(0)
h = np.random.randint(1, 100 ,16).reshape(2,8)
print(h)
print(np.median(h, axis = 0))
print(np.median(h, axis = 1))
print("================")

print(np.nanmedian(np.array([[[np.nan, 2,3,4],[5,66,7,889],[98,7,554,np.nan]]]), axis = 1))

[[45 48 65 68 68 10 84 22]
 [37 88 71 89 89 13 59 66]]
[41.  68.  68.  78.5 78.5 11.5 71.5 44. ]
[56.5 68.5]
[[ 51.5   7.    7.  446.5]]


In [12]:
i = np.array([[1,2], [2,3], [6,9]])
print(np.std(i))

2.7938424357067015


In [13]:
print(np.var(i, axis = 0))
print(np.var(i, axis = 1))

[4.66666667 9.55555556]
[0.25 0.25 2.25]


In [17]:
x = np.random.randint(1, 20, 15).reshape(3, 5)
print(x)
print(np.corrcoef(x))

[[ 6  7  9 18 16]
 [ 5 10 11  2  2]
 [ 8 10  4  7 12]]
[[ 1.         -0.73591052  0.19358774]
 [-0.73591052  1.         -0.45990854]
 [ 0.19358774 -0.45990854  1.        ]]


In [18]:
print(np.correlate([1,2,3,4,5,6,7], [55, 66, 3,4,5]))
print(np.correlate([1,2,3,4,5,6,7], [55, 66, 3,4,5], mode = 'valid'))
print(np.correlate([1,2,3,4,5,6,7], [55, 66, 3,4,5], mode = 'full'))
print(np.correlate([1,2,3,4,5,6,7], [55, 66, 3,4,5], mode = 'same'))

[237 370 503]
[237 370 503]
[  5  14  26 104 237 370 503 596 692 792 385]
[ 26 104 237 370 503 596 692]


In [22]:
z = f.flatten()
np.amax(z)

nan