In [1]:
import numpy as np

In [4]:
with open('one_array.npy', 'wb') as f:
    np.save(f, np.array([1,2,3,4,5]))
np.load('one_array.npy')

array([1, 2, 3, 4, 5])

In [8]:
with open('test.npy', 'wb') as f:
    np.save(f, np.array([1,2,3]))
    np.save(f, np.array([3,2,3]))
    np.save(f, np.array([5,2,3]))
    np.save(f, np.array([7,2,3]))
with open('test.npy', 'rb') as f:
    a = np.load(f)
    b = np.load(f)
    c = np.load(f)
    d = np.load(f)
print(a,b,c,d)

[1 2 3] [3 2 3] [5 2 3] [7 2 3]


In [16]:
e = np.arange(15)
g = np.array([5,6,7,89,4])
h = np.random.rand(16)

with open('multiple_array.npz', 'wb') as f:
    np.savez(f,ar1 = e,ar2 = g,ar3 = h)
maf = np.load('multiple_array.npz')
print(maf['ar1'])
print(maf['ar2'])
print(maf['ar3'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 5  6  7 89  4]
[0.38226119 0.38348065 0.84705308 0.63188425 0.31829265 0.66304952
 0.76315704 0.69323125 0.09023234 0.85462902 0.57286745 0.596232
 0.19814584 0.13343676 0.47995344 0.21213911]


In [19]:
i = np.arange(0,5,1)
i

array([0, 1, 2, 3, 4])

In [21]:
j = np.arange(16).reshape(4,4)
j

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
np.savetxt('test.out', [i], delimiter = ',')
# %load test.out
0.000000000000000000e+00,1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00,4.000000000000000000e+00


(0.0, 1.0, 2.0, 3.0, 4.0)

In [29]:
np.savetxt('test.gz', [i], delimiter = ',')
np.savetxt('test.csv', j, delimiter = ',')

In [31]:
# %load test.csv
0.000000000000000000e+00,1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00
4.000000000000000000e+00,5.000000000000000000e+00,6.000000000000000000e+00,7.000000000000000000e+00
8.000000000000000000e+00,9.000000000000000000e+00,1.000000000000000000e+01,1.100000000000000000e+01
1.200000000000000000e+01,1.300000000000000000e+01,1.400000000000000000e+01,1.500000000000000000e+01


(12.0, 13.0, 14.0, 15.0)

In [34]:
np.savetxt('test.out', [i], fmt = '%1.4e', delimiter = ',', header = 'here comes \nthe header', footer = 'there goes the footer')

In [35]:
# %load test.out
# here comes 
# the header
0.0000e+00
1.0000e+00
2.0000e+00
3.0000e+00
4.0000e+00
# there goes the footer


4.0

In [37]:
np.loadtxt('test.out', delimiter = ',', dtype = 'f4')

array([0., 1., 2., 3., 4.], dtype=float32)

In [45]:
np.genfromtxt("transform.txt", delimiter=',', dtype="i8, i8, U3, U3")

OSError: transform.txt not found.